### ISSUE TITLE
bash: paapi5-python-sdk/setup.py: Permission denied

### ISSUE THREAD

**Issue by jack567ow** [samirsalman/AmazonOffers-TelegramBot#19]
2022-02-12T12:43:15.445241+00:00 heroku[worker.1]: Starting process with command `paapi5-python-sdk/setup.py`
2022-02-12T12:43:16.124651+00:00 heroku[worker.1]: State changed from starting to up
2022-02-12T12:43:16.760408+00:00 app[worker.1]: bash: paapi5-python-sdk/setup.py: Permission denied
2022-02-12T12:43:16.937230+00:00 heroku[worker.1]: Process exited with status 126
2022-02-12T12:43:17.014811+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by luisafurtadodnv** [comment]
I am getting the same error on heroku after running "python bot.py"

Traceback (most recent call last):
  File "/app/bot.py", line 4, in <module>
    from amazon_api import search_items
  File "/app/amazon_api.py", line 1, in <module>
    from paapi5_python_sdk.api.default_api import DefaultApi
ModuleNotFoundError: No module named 'paapi5_python_sdk'

**Comment by luisafurtadodnv** [comment]
[jack567ow](https://github.com/jack567ow) How do you solved this issue?
