### ISSUE TITLE
Bot startup errors

### ISSUE THREAD

**Issue by Alex87a** [samirsalman/AmazonOffers-TelegramBot#22]
Hi, when I go to run the bot I get the following errors:

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version! 
warnings.warn ("urllib3 ({}) or chardet ({}) doesn't match a supported"

Traceback (most recent call last):
File "bot.py", line 5, in <module>
from create_messages import create_item_html
File "/home/Alex/Scrivania/AmazonOffers-TelegramBot-main/create_messages.py", line 1, in <module>
from telegram import InlineKeyboardButton, InlineKeyboardMarkup
ImportError: cannot import name 'InlineKeyboardButton' from 'telegram' (/usr/local/lib/python3.8/dist-packages/telegram/__init__.py)

How can I solve? I did the automatic installation with script.sh

**Comment by d3mo12** [comment]
Same problems , how i can fix it?

**Comment by d3mo12** [comment]
Traceback (most recent call last):
  File "C:\Users\d3mos\OneDrive\Desktop\AmazonOffers-TelegramBot-main\bot.py", line 5, in <module>
    from create_messages import create_item_html
  File "C:\Users\d3mos\OneDrive\Desktop\AmazonOffers-TelegramBot-main\create_messages.py", line 1, in <module>
    from telegram import InlineKeyboardButton, InlineKeyboardMarkup
ImportError: cannot import name 'InlineKeyboardButton' from 'telegram' (C:\Users\d3mos\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\__init__.py)

**Comment by vinceplayer** [comment]
pip install python-telegram-bot==4.0rc1 and i have solved
