### ISSUE TITLE
ModuleNotFoundError: No module named 'paapi5_python_sdk.models'

### ISSUE THREAD

**Issue by Buggher** [samirsalman/AmazonOffers-TelegramBot#25]
Someone can help me to start bot ? I have installed all package manually becouse the command ""bash script.sh"" dont work on windows. After install i start bot with python bot.py but the terminal sends me this error :  

C:\Users\thebu\OneDrive\Desktop\AmazonOffers-TelegramBot-main>python bot.py
Traceback (most recent call last):
  File "C:\Users\thebu\OneDrive\Desktop\AmazonOffers-TelegramBot-main\bot.py", line 4, in <module>
    from amazon_api import search_items
  File "C:\Users\thebu\OneDrive\Desktop\AmazonOffers-TelegramBot-main\amazon_api.py", line 2, in <module>
    from paapi5_python_sdk.models.partner_type import PartnerType
ModuleNotFoundError: No module named 'paapi5_python_sdk.models'

**Comment by nickkkkkkkkkkkkkkkkkk** [comment]
seguo

**Comment by enea1982** [comment]
or same error from me too you have solved?
