### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by enea1982** [samirsalman/AmazonOffers-TelegramBot#33]
who can help me the bot gives me this error

Traceback (most recent call last):
File "bot.py", line 4, in
from amazon_api import search_items
File "/home/demian82/Scrivania/AmazonOffers-TelegramBot-main/amazon_api.py", line 2, in
from paapi5_python_sdk.models.partner_type import PartnerType
ModuleNotFoundError: No module named 'paapi5_python_sdk.models'

**Comment by enea1982** [comment]
@amz_discounts

**Comment by enea1982** [comment]
@Amazon_discounts

**Comment by paoloronco** [comment]
Il mio codice, aggiornato e migliorato, è disponibile per l'acquisto sul sito [telegramdeals-bot.com](https://telegramdeals-bot.com/).
Oltre al codice sorgente, troverai una guida dettagliata per il deploy.
Con il coupon code githubcode-paoloronco è possibile ottenere uno sconto aggiuntivo
