### ISSUE TITLE
paapi5_python_sdk.models not found

### ISSUE THREAD

**Issue by annalamboglia** [samirsalman/AmazonOffers-TelegramBot#7]
Although I have installed the library it tells me that it cannot find the paapi5_python_sdk.models module, is it possible that there have been problems and that the library is out of date?

**Comment by Alex87a** [comment]
@annalamboglia @junkscript have you managed to solve?

**Comment by nickkkkkkkkkkkkkkkkkk** [comment]
Attualmente esce ancora errore......🤷‍♂️🤷‍♂️🤷‍♂️

C:\Users\Nico\Downloads\Compressed\amazon-telegram-main>python bot.py
Traceback (most recent call last):
  File "C:\Users\Nico\Downloads\Compressed\amazon-telegram-main\bot.py", line 4, in <module>
    from amazon_api import search_items
  File "C:\Users\Nico\Downloads\Compressed\amazon-telegram-main\amazon_api.py", line 2, in <module>
    from paapi5_python_sdk.models.partner_type import PartnerType
ModuleNotFoundError: No module named 'paapi5_python_sdk.models'

**Comment by bernardomascellani** [comment]
Hi, I have the same problem:

amazon_api.py", line 2, in <module>
    from paapi5_python_sdk.models.partner_type import PartnerType
ModuleNotFoundError: No module named 'paapi5_python_sdk.models'

How fix this?
Thanks!
